server:
  port: 8090

debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    yun.jung.kim.Host_Api: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/host_api
    #username: host_api
    #password: host#test@pwd
    username: root
    password: root!!root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always